default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: "yourpassword"

development:
  <<: *default
  database: ratemygym_development

test:
  <<: *default
  database: ratemygym_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: postgresql://himat_user:VTUoIZ5jd6uGjnGSoVwXRWqmqZE2dHBi@dpg-cs91dsjqf0us738hheig-a/himat<%= ENV['DATABASE_URL'] %>  # This is the DATABASE_URL from Render
